on:
  push:
    branches: [main]

...

- name: Build image
  run: docker build -t $IMAGE_NAME:${{ github.sha }} .

...

- name: Tag and push
  run: |
    FULL=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
    docker tag $IMAGE_NAME:${{ github.sha }} $FULL:${{ github.sha }}
    docker tag $IMAGE_NAME:${{ github.sha }} $FULL:latest
    docker push $FULL:${{ github.sha }}
    docker push $FULL:latest