name: CI Docker

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: workshop-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.20.1
        with:
          image-ref: $IMAGE_NAME:${{ github.sha }}
          severity: CRITICAL
          exit-code: 1

      - name: Tag and push
        run: |
          FULL=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
          docker tag $IMAGE_NAME:${{ github.sha }} $FULL:${{ github.sha }}
          docker tag $IMAGE_NAME:${{ github.sha }} $FULL:latest
          docker push $FULL:${{ github.sha }}
          docker push $FULL:latest